[project]
name = "cinemabot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.24.0",
    "aiosqlite>=0.22.1",
    "dotenv>=0.9.9",
    "playwright>=1.57.0",
]
